rgname                 = "pf-rg-staging"
service_principal_name = "pf-spn-staging"
keyvault_name          = "pf-kv-101-staging"
SUB_ID = ""
node_pool_name = "pf-nodepool-staging"
cluster_name = "pf-cluster-staging"
